//
// Created by Kry0m on 03/10/2023.
//

#ifndef PROYECTO_FLUIDOS_ARQUITECTURA_PROGARGS_HPP
#define PROYECTO_FLUIDOS_ARQUITECTURA_PROGARGS_HPP

int function (int argument);

#endif //PROYECTO_FLUIDOS_ARQUITECTURA_PROGARGS_HPP
